<?xml version="1.0" encoding="UTF-8"?>
<response><action>system/get_info</action><timezone>America/Chicago</timezone><timezone_offset>-18000</timezone_offset><image_sizes><image_size><width>32</width><height>32</height><thumbnail>0</thumbnail></image_size><image_size><width>107</width><height>80</height><thumbnail>1</thumbnail></image_size><image_size><width>191</width><height>145</height><thumbnail>2</thumbnail></image_size><image_size><width>335</width><height>251</height><thumbnail>3</thumbnail></image_size><image_size><width>515</width><height>386</height><thumbnail>4</thumbnail></image_size><image_size><width>800</width><height>600</height><thumbnail>5</thumbnail></image_size><image_size><width>1024</width><height>768</height><thumbnail>6</thumbnail></image_size><image_size><width>1280</width><height>800</height><thumbnail>7</thumbnail></image_size><image_size><width>1600</width><height>1200</height><thumbnail>8</thumbnail></image_size><image_size><width>1680</width><height>1050</height><thumbnail>9</thumbnail></image_size><image_size><width>1920</width><height>1080</height><thumbnail>a</thumbnail></image_size><image_size><width>2240</width><height>1680</height><thumbnail>b</thumbnail></image_size><image_size><width>2560</width><height>1920</height><thumbnail>c</thumbnail></image_size><image_size><width>3072</width><height>2304</height><thumbnail>d</thumbnail></image_size><image_size><width>3264</width><height>2448</height><thumbnail>e</thumbnail></image_size><image_size><width>4064</width><height>2704</height><thumbnail>f</thumbnail></image_size><image_size><width>8000</width><height>8000</height><thumbnail>z</thumbnail></image_size></image_sizes><viewable><extensions><extension>json</extension><extension>doc</extension><extension>pdf</extension><extension>rtf</extension><extension>xls</extension><extension>ppt</extension><extension>odg</extension><extension>odp</extension><extension>ods</extension><extension>odt</extension><extension>ac3</extension><extension>gif</extension><extension>png</extension><extension>css</extension><extension>csv</extension><extension>js</extension><extension>tsv</extension><extension>ogv</extension><extension>xlsm</extension><extension>ppsm</extension><extension>docm</extension><extension>ppsx</extension><extension>xlsx</extension><extension>xltx</extension><extension>docx</extension><extension>dotx</extension><extension>sxi</extension><extension>sxw</extension><extension>pl</extension><extension>sh</extension><extension>tcl</extension><extension>wma</extension><extension>wav</extension><extension>bmp</extension><extension>tga</extension><extension>webm</extension><extension>flv</extension><extension>wmv</extension><extension>avi</extension><extension>wks</extension><extension>wps</extension><extension>xhtml</extension><extension>xhtm</extension><extension>mp3</extension><extension>ogg</extension><extension>jpg</extension><extension>jpeg</extension><extension>jpe</extension><extension>jfif</extension><extension>tiff</extension><extension>tif</extension><extension>html</extension><extension>htm</extension><extension>txt</extension><extension>asc</extension><extension>text</extension><extension>h</extension><extension>cc</extension><extension>cxx</extension><extension>xml</extension><extension>3gp</extension><extension>3gpp</extension><extension>3g2</extension><extension>3gpp2</extension><extension>mp4</extension><extension>mpg4</extension><extension>mpeg</extension><extension>mpg</extension><extension>mov</extension><extension>aiff</extension><extension>zzz</extension><extension>pptx</extension><extension>pps</extension><extension>rtf</extension><extension>cpp</extension><extension>rtf</extension><extension>mkv</extension><extension>doc</extension><extension>mod</extension><extension>php</extension><extension>c</extension><extension>php3</extension><extension>php4</extension><extension>php5</extension><extension>phps</extension><extension>ini</extension><extension>bat</extension><extension>bsh</extension><extension>cob</extension><extension>hpp</extension><extension>java</extension><extension>jsp</extension><extension>mak</extension><extension>phtml</extension><extension>phtml</extension><extension>phtml</extension><extension>phtml</extension><extension>py</extension><extension>shtml</extension><extension>shtml</extension><extension>sql</extension><extension>vb</extension><extension>vbs</extension><extension>vbs</extension><extension>vbs</extension><extension>conf</extension><extension>inf</extension><extension>m4v</extension><extension>csv</extension><extension>vob</extension><extension>m4v</extension><extension>abw</extension><extension>ogg</extension><extension>mp3</extension><extension>wma</extension><extension>oga</extension><extension>mp4</extension><extension>mkv</extension><extension>ogv</extension><extension>wma</extension><extension>m4a</extension><extension>m4a</extension><extension>ogg</extension><extension>avi</extension><extension>mov</extension><extension>mpg</extension><extension>ogv</extension><extension>flv</extension><extension>3gp</extension><extension>vob</extension><extension>wmv</extension><extension>aac</extension><extension>ac3</extension><extension>xcf</extension></extensions></viewable><editable><extensions><extension>json</extension><extension>css</extension><extension>csv</extension><extension>js</extension><extension>pl</extension><extension>sh</extension><extension>tcl</extension><extension>xhtml</extension><extension>xhtm</extension><extension>html</extension><extension>htm</extension><extension>txt</extension><extension>text</extension><extension>h</extension><extension>cc</extension><extension>cxx</extension><extension>xml</extension><extension>cpp</extension><extension>php</extension><extension>c</extension><extension>php3</extension><extension>php4</extension><extension>php5</extension><extension>phps</extension><extension>ini</extension><extension>bat</extension><extension>bsh</extension><extension>cob</extension><extension>hpp</extension><extension>java</extension><extension>jsp</extension><extension>mak</extension><extension>phtml</extension><extension>phtml</extension><extension>phtml</extension><extension>phtml</extension><extension>py</extension><extension>shtml</extension><extension>shtml</extension><extension>sql</extension><extension>vb</extension><extension>vbs</extension><extension>vbs</extension><extension>vbs</extension><extension>conf</extension><extension>inf</extension><extension>csv</extension></extensions></editable><terms_of_service><revision>3.11</revision><terms>&lt;style&gt;&#13;
body{font-family:"Open Sans",sans-serif;}&#13;
&lt;/style&gt;&#13;
&#13;
&lt;h1&gt;&lt;strong&gt;MediaFire Terms of Service&lt;/strong&gt;&lt;/h1&gt;&#13;
&#13;
&lt;h2&gt;Acknowledgement&lt;/h2&gt;&#13;
&#13;
&lt;p&gt;Welcome to MediaFire!  This MediaFire Terms of Service, in conjunction with the Privacy Policy and other terms and conditions of use which are incorporated herein by reference and which may be posted and applicable to specific services (collectively, the "Agreement") governs your access to and use of the MediaFire website, Content, apps, software, products and services provided to you on, from, or through the MediaFire website, (collectively, the "Services").  Regardless of whether you have a subscription, are a registered user, or are simply downloading from a shared link which does not require a registered account, all such interactions with the MediaFire website and use of any Services is an explicit acceptance of this Agreement signifying you have read, understand, and agree to be bound by all of the terms of this Agreement which is a LEGALLY BINDING CONTRACT.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;If you are using the Services on behalf of a company, organization or branch of government, you affirm that you have the authority to accept this Agreement on behalf of your company or organization and all references herein to ‘you’ or ‘your’ will refer not only to yourself but also to the company or organization.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;IF YOU DO NOT FULLY AND COMPLETELY AGREE TO THE TERMS OF THE AGREEMENT AND YOU, AS A RESPONSIBLE USER, CHOOSE TO CONTINUE TO USE THE SERVICES, YOU WILL BE BOUND TO THE TERMS OF THE AGREEMENT.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;MediaFire (also referred herein as “us”, “we” or “our”) may modify the Agreement which will become effective immediately upon its posting to the website. Your continued use of the website and any associated services indicates your acceptance of changes to the Agreement and you agree to be bound by such modification or revisions. If you are dissatisfied with anything related to the MediaFire website, your sole remedy is to discontinue use of the Services. You use the Services of MediaFire at your own risk. Nothing in the Agreement shall be deemed to confer any third-party rights or benefits.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;&lt;em&gt;Which means:  The above states that you have read and agree to the Terms of Service and Privacy Policy, and any future changes, if you use MediaFire for yourself or your company or organization now or after modifications to this Agreement.&lt;/em&gt;&lt;/p&gt;&#13;
&#13;
&lt;h2&gt;Ability to Accept Terms of Service&lt;/h2&gt;&#13;
&#13;
&lt;p&gt;MediaFire Free Services are available to anyone over the age of 13, in observance of and compliance with the Children's Online Privacy Protection Act. If you are under 13 years of age, then do not use the Service. There are lots of other great web sites for you. Talk to your parents about what sites are appropriate for you.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;MediaFire premium services are available to anyone over the age of 18.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Accounts for business, organizations or government entities must be created and maintained by an individual capable of and authorized to enter into binding contracts on behalf of the entity. You affirm that you are fully able to enter into, abide by and comply with the terms, conditions, obligations, affirmations, representations, and warranties set forth in this Agreement.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;&lt;em&gt;Which means: You’re over 18 and have authority and permission to accept this Agreement or between 13 and 18 and your parents have accepted this Agreement on your behalf.&lt;/em&gt;&lt;/p&gt;&#13;
&#13;
&lt;h2&gt;Content – It’s Yours&lt;/h2&gt;&#13;
&#13;
&lt;p&gt;When you upload text, software, scripts, graphics, photos, sounds, music, videos, audiovisual combinations, interactive features and other materials that may be viewed on, or accessed through the Services, we refer to it as “Content”.  You affirm, represent, and warrant that you own or have the necessary licenses, rights, consents, and permissions to store, share or distribute the Content.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;You retain all of your ownership rights in your Content. We don’t claim any ownership in or to any of your Content.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;&lt;em&gt;Which means:  If you created it, it’s yours.   If any piece of it was created by someone else, you swear you have their permission to store it for your own use or share it.  We don’t claim we own any of it.&lt;/em&gt;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;To enable MediaFire to provide the Services, it is necessary for you to hereby grant MediaFire a worldwide, non-exclusive, royalty-free, sub-licensable and transferable limited license to use, reproduce, distribute, prepare derivative works of, or display Content in connection with the Services. &lt;/p&gt;&#13;
&#13;
&lt;p&gt;&lt;em&gt;Which means:  You give us limited permission to do what you need us to do, like show your Content to you or people you share it with, store it on our servers and make redundant backups so there is more than one copy of it.&lt;/em&gt;&lt;/p&gt;&#13;
&#13;
&lt;h2&gt;It’s All About You&lt;/h2&gt;&#13;
&#13;
&lt;p&gt;You control your Content through your account and/or cookies which may be placed on your computer or other devices. &lt;/p&gt;&#13;
&#13;
&lt;p&gt;You are responsible for any costs associated with your Content and use of the MediaFire Services.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;You are solely responsible for your Content and your interactions with other users of the Services. &lt;/p&gt; &#13;
&#13;
&lt;p&gt;When you allow other users access to your Content, you, not MediaFire, are responsible for what others do with it.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;You agree, while using MediaFire Services, that you may not:&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Alter or modify any part of the Services;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Use the Services for any illegal purpose;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Use any robot, spider, offline readers, site search and/or retrieval application, or other device to retrieve or index any portion of the Services, with the exception of public search engines;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Transmit any viruses, worms, defects, Trojans or other items of a contaminating or destructive nature, except when transmitting to a knowing recipient while conducting security research;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Distribute any Content that includes code hidden or otherwise contained within the Content which is unrelated to the Content;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Reformat or frame any portion of any web page that is part of the Services without the express permission of MediaFire;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Collect or harvest any personal identifiable information or account names or solicit users;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Impersonate another person, whether real or fictional;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Permit any third parties to use your name and password;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Violate or attempt to violate MediaFire systems or interfere with the normal use of the Services by users;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Resale MediaFire's products and Services;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Post advertisements, promotions or solicitations of business;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Transmit any form of solicitation or Spam;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Distribute any Content that falsely implies sponsorship of the Content by the Services, falsify or delete any author attribution in any Content, or promote any information that you know is false or misleading;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Distribute an illegal or unauthorized copy of another person's trademarked or copyrighted work;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Distribute Content that is libelous, defamatory, obscene, pornographic, abusive, harassing, threatening, unlawful or promotes or encourages illegal activity;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Distribute Content that violates the rights of others, such as distributing Content that infringes any copyright, trademark, patent, trade secret, or violates any right of privacy or publicity, or that is libelous or defamatory, or that directs any user to the content of a third party without consent of the third party;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Defame or libel any person; invade any person's right of privacy or publicity or otherwise violate, misappropriate or infringe the rights of any person;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Export or re-export Content in violation of the export or import laws of the United States or without all required approvals, licenses and exemptions;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Distribute any links to any external Internet sites that are obscene or pornographic, or distribute pornographic or sexually explicit material of any kind.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;In addition to the general restrictions above, the following restrictions and conditions apply specifically to your use of the Content. You will comply with United States laws regarding transmission of data.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Content is provided to you AS IS. You understand that when using the Services, you will be exposed to Content from a variety of sources, and that MediaFire is not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such Content. You further understand and acknowledge that you may be exposed to Content that is inaccurate, offensive, indecent, or objectionable, and you agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against MediaFire with respect thereto, and, to the extent permitted by applicable law, agree to indemnify and hold harmless MediaFire, its owners, operators, affiliates, licensors, and licensees to the fullest extent allowed by law regarding all matters related to any Content and your use of the Services. You acknowledge your use of Content is at your sole risk.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;&lt;em&gt;Which means:  Play Nice.   You are solely responsible for everything you share or any interactions you have through MediaFire.&lt;/em&gt;&lt;/p&gt;&#13;
&#13;
&lt;h2&gt;Account Safeguards&lt;/h2&gt;&#13;
&#13;
&lt;p&gt;To access or benefit from the Services or features on MediaFire, you may have to create a MediaFire account. You are responsible for maintaining the confidentiality of your access information and are responsible for all activities that occur utilizing your information. You should only access your MediaFire account from a trusted network.   Although MediaFire will not be liable for any losses you might suffer, you may be liable for the losses of MediaFire or others.&lt;/p&gt;&#13;
&#13;
&lt;h2&gt;MediaFire &amp; Services&lt;/h2&gt;&#13;
&#13;
&lt;p&gt;MediaFire does not endorse any Content, including, but not limited to, its accuracy, completeness, appropriateness or legality, stored on or distributed through the Services and MediaFire expressly disclaims any and all liability in connection with Content.   Content is yours, not ours.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;MediaFire Content may contain links to external sites; however, MediaFire is not responsible for any availability of or the content on or through any external site.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;MediaFire maintains multiple copies of active files, however, MediaFire bears no responsibility for maintaining your data indefinitely.  You bear full responsibility and sole liability for any corrupted, lost or irrecoverable data. You understand and agree that MediaFire reserves the right to delete, move, archive (including account information) or edit any Content that it may determine violates the Agreement and/or Privacy Policy or is otherwise unacceptable and may terminate your access to the Services, without prior notice and at its sole discretion.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;When MediaFire removes or disables Content for policy violations, the user who posted the Content may receive a strike. The user is notified of the violation. Repeated policy violations may result in account termination.  MediaFire reserves the right to determine what is harmful to its users, operations, or reputation including any activities that restrict or inhibit any other user from using and enjoying the Services. Complaints about violators of our policies should be submitted to our abuse department. Each complaint will be investigated and appropriate action will be taken.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;MediaFire premium accounts file transactions below a minimum of 100KB will be registered as 100KB transactions.  Additionally, premium accounts are limited to initiating no more than 1 million (1,000,000) transfers per month.  Non-premium accounts have no transfer limits.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;MediaFire reserves the right to terminate your access to any and/or all parts of the Services at any time for any reason without prior notice or liability. The terms of the Agreement and Privacy Policy shall survive any termination of your access to the Services.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;MediaFire may change, suspend or discontinue all or any aspect of the Services at any time, including the availability of any feature, database, or Content, without prior notice or liability.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Light patterns, like those which might be displayed when using the Services, may result in epileptic seizures in some people. Discontinue use of the Services, if advised by your physician or you experience epileptic symptoms.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;&lt;em&gt;Which means:  You are solely responsible for your Content.  Important data should be stored in more than one place.  When receiving Content from a 3rd party, always exercise caution.&lt;/em&gt;&lt;/p&gt;&#13;
&#13;
&lt;h2&gt;Software, Applications, Modifications &amp; License&lt;/h2&gt;&#13;
&#13;
&lt;p&gt;MediaFire Services may include special applications, application programming interfaces, installable software, or developer resources you can download and install on your desktop, mobile phone or other devices with Internet capability to enhance your ability to interact and benefit from the Services (“Software”).    This Software may require periodic modifications/updates, which may occur automatically or require you to initiate them.   The Software is a copyrighted work of MediaFire and is governed by the terms of this Agreement.  MediaFire grants you a “Limited License” to use the Software solely to interact with the Services.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;When you download and/or use the Software, you accept this Limited License. MediaFire grants you a personal, non-exclusive, non-assignable, non-transferable, worldwide, royalty-free limited license to use the Software on any device you own or control.  This Limited License is for the sole purpose of enabling you to use and enjoy the benefit of the Services as provided by MediaFire, in the manner permitted by this Agreement.  You may not rent, lease, lend, sell, trade, redistribute, assign or sublicense your rights to use the Software, grant a security interest in or over your rights to use the Software, or otherwise transfer any part of your rights to use the Software. You may not, or permit anyone else to, copy (except as expressly permitted by this license), decompile, reverse engineer, disassemble, attempt to derive the source code of, modify, or create derivative works of the Software, any updates, or any part thereof (except as and only to the extent any foregoing restriction is prohibited by applicable law or to the extent as may be permitted by the licensing terms governing use of any open sourced components included with the Software). Any attempt to do so is a violation of the rights of MediaFire and its licensors. If you breach this restriction, you may be subject to prosecution and damages. The terms of the Limited License will govern any upgrades provided by MediaFire that replace and/or supplement the original Software, unless such upgrade is accompanied by a separate license, in which case the terms of that license will govern.  &lt;/p&gt;&#13;
&#13;
&lt;p&gt;Nothing in this Agreement grants you any right, title, or interest in the Services, Software or Content (other than your own) or to use any MediaFire trademark, logo, domain name (or any derivative thereof), branding or features.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;&lt;em&gt;Which means:  MediaFire will offer you the ability to download and use new applications from time to time and may update the software periodically.   MediaFire owns all its software and applications, regardless of who provided input or may make modifications to it, and only you may use it under this licensing agreement.&lt;/em&gt;&lt;/p&gt;&#13;
&#13;
&lt;h2&gt;DMCA: Digital Millennium Copyright Act&lt;/h2&gt;&#13;
&#13;
&lt;p&gt;If your copyrighted or trademarked works are being distributed through the Services without your permission, please see our Copyright page for information on how to make a claim.   Claims will be processed in accordance with United States law. &lt;/p&gt; &#13;
&#13;
&lt;p&gt;&lt;em&gt;Which means:  Go to the Copyright page for legal guidelines, contact us, and we’ll respond ASAP.&lt;/em&gt;&lt;/p&gt;&#13;
&#13;
&lt;h2&gt;MediaFire Premium Accounts - Payment, Renewal and Cancellation&lt;/h2&gt;&#13;
&#13;
&lt;p&gt;Premium Services (“Subscription”) require you to pay a fee, which is described in greater detail below.  You agree to pay all fees and charges you incur, in US dollars with a major credit card accepted by MediaFire.  Subscription fees are non-refundable except as expressly set forth below.  You hereby authorize us to charge your credit card to pay for the ongoing cost of Subscription.  Payment for the appropriate Subscription and/or Services will be made by automatic charges to your credit card.  Upon its expiration, your Subscription will be automatically renewed for a term (1) equal to the original subscription term or (2) in accordance with the terms of a special subscription offer (“Promotion”), and continually renewed for equal terms thereafter, unless you terminate your Subscription pursuant to the process set forth below.  You acknowledge and agree that the authorization to charge your credit card for our Subscriptions shall automatically transfer to any successors or assigns of the Services.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;The billing period ends each term on the anniversary of your activation date. You agree to pay all fees and charges that you incur through your account, including, but not limited to, applicable taxes.  You will be responsible for charges for any products or services that you purchase that are offered for sale through our Services.  In addition, you are responsible for paying any amounts billed to your credit card by someone who uses your card, such as a secondary card holder or family member, or if you authorized use of your card by someone else for the initial Subscription. If payment cannot be charged to your credit card or your payment is returned to us for any reason, including chargeback, we reserve the right to either suspend or terminate your account and our obligations under this Agreement.  If you provide us with a new/updated card and are successfully charged, your renewal period will be based on the original renewal date and not the date of the successful charge.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;PROMOTIONAL SUBSCRIPTIONS ARE RENEWED AT THE THEN CURRENT NON-PROMOTIONAL FEE. SOME YEARLY PLANS, WERE OFFERED FOR THE INITIAL 12 MONTHS ONLY AND MAY BEGIN BILLING MONTHLY STARTING THE 13TH MONTH AFTER SIGNUP. From time to time, we may offer different subscription plans and the fees for such plans may vary.   A detailed description of current premium services and features can be found on the Product Matrix page or by contacting Customer Service.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Business services offer "Rollover Bandwidth". Unused bandwidth in each billing period will become available in subsequent billing periods, without time limitations for usage. If you upgrade your plan, you will be billed immediately for the new plan and any unused bandwidth from your previous plan will be rolled over into your new plan. Additional increments of bandwidth may be purchased for immediate use, which qualifies as Rollover Bandwidth. This one time purchase is not a recurring charge and will not affect the pricing of your Subscription service. You may view your billing history from your My Account page.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Pro services will be allocated 500GB of total storage, and a minimum of 1TB of bandwidth every 30 days, based on your initial subscription date.  Additional increments of bandwidth may be purchased.  If you have less than 1TB available at the beginning of the next 30 day period, your bandwidth will be automatically increased to 1TB.   If your account is in excess of 1TB, bandwidth will not be added or deducted&#13;
&#13;
&lt;p&gt;Bandwidth in a premium account is consumed by anyone, including you, who download your file(s). From your My Account page, you may view stats about your bandwidth usage.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;You may cancel a Subscription at any time through your My Account page. Your account will remain active for the remainder of the term for which you have previously paid after which it will revert to a standard free account and be subject to the restrictions of a free account. Cancellation of your Subscription will not relieve you of any obligations to pay accrued charges, including any prorated charges accrued for the billing cycle in which your Subscription is cancelled.  We are not responsible for any accounting errors or oversights older than sixty (60) days.  MediaFire may, without compensation or proration, cancel your Subscription in the event of nonpayment or dispute of payment or if you violate any terms or conditions of this Agreement.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;&lt;em&gt;Which means:  Your credit card will automatically be charged for renewals.   Promotional and some yearly subscription plans, at renewal, are billed monthly at the then current fee.  You can cancel at any time from your account, or contact customer service.   You can buy an upgraded account or services.  Bandwidth is used by anyone downloading your Content.&lt;/em&gt;&lt;/p&gt;&#13;
&#13;
&lt;h2&gt;Refund Policy:&lt;/h2&gt;&#13;
&#13;
&lt;p&gt;MediaFire may approve a thirty (30) day money-back guarantee, after a review of Services utilized, which would apply only to the initial charge of your first Subscription with MediaFire. The guarantee does not apply to re-established subscriptions, changes in subscriptions or creations of subsequent subscriptions.  Your account will then revert to a free account and be subject to the restrictions of a free account.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;REFUND REQUESTS should be submitted to MediaFire by email at &lt;a class="pig_latin" href="ailtomay:efundray@ediafiremay.omcay"&gt;efundray@ediafiremay.omcay&lt;/a&gt;.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;&lt;em&gt;Which means:  First time users may request a refund of their first month Subscription fee and be converted to a free account user.&lt;/em&gt;&lt;/p&gt;&#13;
&#13;
&lt;h2&gt;As-Is Services&lt;/h2&gt;&#13;
&#13;
&lt;p&gt;YOU AGREE THAT YOUR USE OF THE SERVICES SHALL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, MEDIAFIRE, ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE SERVICES AND YOUR USE THEREOF.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;NEITHER MEDIAFIRE NOR ANY PROVIDER OF ANY THIRD PARTY CONTENT WARRANTS THAT THE SERVICES WILL BE UNINTERRUPTED OR ERROR FREE OR MAKES ANY WARRANTY OF THE RESULTS TO BE OBTAINED FROM USE OF THE SERVICES OR CONTENT. BOTH THE SERVICES AND CONTENT ARE DISTRIBUTED ON AN "AS IS, AS AVAILABLE" BASIS. NEITHER MEDIAFIRE NOR ANY THIRD PARTY MAKES ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRANTIES OF TITLE OR IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, WITH RESPECT TO THE SERVICES OR CONTENT OR ANY PRODUCTS OR SERVICES SOLD THROUGH THE SERVICES.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;NEITHER MEDIAFIRE NOR ANY THIRD PARTY WARRANT THAT ANY FILES AVAILABLE FOR DOWNLOADING THROUGH THE SERVICES WILL BE FREE OF VIRUSES OR SIMILAR CONTAMINATION OR DESTRUCTIVE FEATURES. YOU AGREE THAT YOU ASSUME ALL RISK AS TO THE QUALITY AND PERFORMANCE OF THE SERVICES AND THE ACCURACY AND COMPLETENESS OF THE CONTENT. MEDIAFIRE IS NOT RESPONSIBLE OR LIABLE FOR ANY UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR CONTENT OR FOR ANY VIOLATION OF ITS AGREEMENT.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;FOR CLARITY, MEDIAFIRE ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR SERVICES, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR SERVICES, (V) ANY BUGS, VIRUSES, TROJANS, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH OUR SERVICES BY ANY THIRD PARTY, AND/OR (VI) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SERVICES. MEDIAFIRE DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE SERVICES OR ANY HYPERLINKED SERVICES OR FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND MEDIAFIRE WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES. AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;&lt;em&gt;Which means:   Standard contract capitalized language.   Internet services are great but nothing is perfect and we’re not responsible if something goes wrong.&lt;/em&gt;&lt;/p&gt;&#13;
&#13;
&lt;h2&gt;Limitation of Liability&lt;/h2&gt;&#13;
&#13;
&lt;p&gt;NEITHER MEDIAFIRE NOR ANY THIRD PARTY PROVIDER SHALL BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES WHATSOEVER ARISING OUT OF THE USE OF OR INABILITY TO USE THE SERVICES, EVEN IF SUCH PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT WILL MEDIAFIRES AGGREGATE LIABILITY TO YOU OR ANY THIRD PARTY FOR ANY AND ALL CLAIMS ARISING OUT OF OR IN CONNECTION WITH THE USE OF THE SERVICES EXCEED ONE HUNDRED DOLLARS ($100). THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN MEDIAFIRE AND YOU. IN STATES, COUNTRIES OR TERRITORIES NOT ALLOWING EXCLUSION OF IMPLIED WARRANTIES OR LIMITATION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, MEDIAFIRE AND ANY THIRD PARTY PROVIDER SHALL BE LIMITED TO THE GREATEST EXTENT OF THE LAW.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;The Services are controlled and offered by MediaFire from its facilities in the United States of America. MediaFire makes no representations that the Services are appropriate or available for use in other locations. Those who access or use the Services from other jurisdictions do so at their own volition and are responsible for compliance with local law.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;&lt;em&gt;Which means:  Also standard contract capitalized language.    This clarifies that we limit our responsibility if something goes wrong.&lt;/em&gt;&lt;/p&gt;&#13;
&#13;
&lt;h2&gt;Indemnity&lt;/h2&gt;&#13;
&#13;
&lt;p&gt;You agree to indemnify, defend and hold MediaFire and its affiliates, and both MediaFire and their respective officers, directors, owners, employees, agents, information providers and licensors harmless from and against any and all claims, liability, losses, damages, obligations, costs and expenses, including attorney's fees, incurred by any MediaFire Party in connection with any Content or use of the Services, whether via your password and/or by any other person, whether or not authorized by you. MediaFire reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, and in such case, you agree to cooperate with MediaFire's defense of such claim. This defense and indemnification obligation will survive these Terms of Service and your use of the Services.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;&lt;em&gt;Which means:  If we get in trouble because of something you did or should have done, you’ll defend us in court or help us defend ourselves.&lt;/em&gt;&lt;/p&gt;&#13;
&#13;
&lt;h2&gt;Miscellaneous Legal&lt;/h2&gt;&#13;
&#13;
&lt;p&gt;The Agreement, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by MediaFire without restriction.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;The Agreement shall be construed in accordance with the laws of the State of Texas, without reference to principles of choice of law. You and MediaFire each irrevocably consent to the personal jurisdiction of the federal or state courts located in Harris County, Texas ("Courts") with respect to any action, suit or proceeding arising out of or related to the Agreement or to the Services and /or Content and waive any objection to venue in any of the Courts for such an action, suit or proceeding; additionally, you agree that you will not bring any such action, suit or proceeding in any court other than the Courts.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;These Terms of Service, together with the Privacy Policy and any other legal notices published by MediaFire on the Services, the Agreement, constitutes the entire agreement between the parties with respect to the subject matter hereof, and supersedes all previous written or oral agreements between the parties with respect to such subject matter. If any inconsistency exists between the terms of the Agreement and any additional terms and conditions posted on the Services, such terms shall be interpreted as to eliminate any inconsistency, if possible, and otherwise, the additional terms and conditions shall control. If any provision of the Agreement is held invalid, illegal or unenforceable in any respect, (i) such provision shall be interpreted in such a manner as to preserve, to the maximum extent possible, the intent of the parties, (ii) the validity, legality and enforceability of the remaining provisions shall not in any way be affected or impaired thereby, and (iii) such decision shall not affect the validity, legality or enforceability of such provision under other circumstances.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;No failure in delay in exercising or enforcing this policy shall constitute a waiver of the Agreement or any other right or remedy. If any provision of the Agreement is deemed unenforceable due to law or change in law, such a provision shall be disregarded and the balance of the Agreement shall remain in effect.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;YOU AND MEDIAFIRE AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ARISES, OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;&lt;em&gt;Which means:  Standard contract language.  All disagreements will be heard in Harris County, Texas, USA within one year.&lt;/em&gt;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Please submit reports of any violations to our support department.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Revised: March 15, 2017&lt;/p&gt;</terms><date>2018-03-06 16:08:58</date><date_utc>2018-03-06T22:08:58Z</date_utc></terms_of_service><privacy_policy><revision>1.47</revision><terms>&lt;h1&gt;&lt;strong&gt;MediaFire’s Privacy Policy and User Notice&lt;/strong&gt;&lt;/h1&gt;&#13;
&lt;p&gt;&lt;/p&gt;&#13;
&#13;
&lt;h2&gt;Introduction&lt;/h2&gt;&#13;
&lt;p&gt;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;MediaFire recognizes and believes that data privacy is essential to all Internet users, and the privacy of your personal information is of the utmost importance to us. We are committed to providing you an experience that is safe, secure, and trustworthy. Part of this commitment means safeguarding and respecting your privacy and your choices.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;This Privacy Notice explains what information we collect, how we use it and what choices you have about it, in addition to information on disclosure, retention, and protection of your personal information.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Because we’re a technology company, some of the concepts below are a little technical, but we’ve tried our best to explain things in a simple and clear way. This Privacy Policy gives you an overview of all possible situations in which we could interact together. Of course, all situations may not apply to you.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;This Privacy Policy, in conjunction with our Terms of Service, collectively referred to as the "Agreement", governs your use of the MediaFire website, Content, apps, software, products, applications, tools and services provided to you on, from, or through the MediaFire website or platform regardless of how your access or use them (collectively, the "Services").  Where we provide the Services under contract with an organization (for example your employer) that organization controls the information processed by the Services. “User”, “You” and “Your” refers to you, the person accessing this website and accepting MediaFire’s Privacy Policy and Terms and Conditions.  “We”, “Us”, and “Ourselves” refers to MediaFire. “Party”, “Parties”, or “Us”, refers to both you and ourselves.  It doesn’t matter if the words are capitalized or not.  If you choose not to accept this Policy, please do not access or use our Services or interact with any other aspect of our business.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;All topics are covered in greater detail below.&lt;/p&gt;&#13;
&#13;
&lt;h2&gt;Overview&lt;/h2&gt;&#13;
&lt;p&gt;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;We want you to fully understand how we may collect, use, and share data relating to you, our legal basis, your rights and the choices that are available to you.&lt;/p&gt;&#13;
&#13;
&lt;h2&gt;This Privacy Policy incorporates:&lt;/h2&gt;&#13;
&lt;p&gt;&lt;/p&gt;&#13;
&#13;
&lt;ul style="list-style: initial; margin: initial; padding: 0 0 0 40px;"&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;Better navigation and user-friendly language. To make the policy easier to understand, we use clear, plain language and examples that illustrate our activities.&lt;/li&gt;&#13;
&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;Insights into how we acquire your information and how it is used.&lt;/li&gt;&#13;
&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;More control over your information. We provide intelligence on how you can control the information you provide to us. Our policy explains how you can make choices about your information, and the measures we’ve put in place to keep your information secure.&lt;/li&gt;&#13;
&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;More about using our products for work. Many users have access to our services through their organizations (e.g., their employers), who control their accounts or use of our Services. The updated policy clarifies our relationship to these users and explains the tools available to administrators of these users.&lt;/li&gt;&#13;
&lt;/ul&gt;&#13;
&#13;
&lt;h2&gt;What is Personal and Non Personal Information?&lt;/h2&gt;&#13;
&lt;p&gt;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Personally Identifiable Information, commonly referred to as PII, is information that itself may identify a unique individual or can be linked back to an individual, directly or indirectly, by reference to an identifier such as a name, an online or device identifier, an identification number, or location data such as your IP address.  In relation to your interaction with MediaFire, personal information, for example, may include information you may purposefully provide such as your name and email address during account registration or your address and financial information if you make a purchase.   By visiting our website, we automatically collect your IP address.  Upon your request and in order for us to download or distribute any Content uploaded by you to MediaFire, your files become published Content and cannot be considered personally identifiable information.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Non-personally identifiable information cannot be used to identify or locate an individual person.  Examples are: hashed/anonymized/pseudonymized data, click stream information, browser type, demographics, time and date, which advertisements are clicked or scrolled over and other data of interest.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;We will not share personal information about you or any of your Content with any third parties except as described in this Privacy Notice.&lt;/p&gt;&#13;
&#13;
&lt;h2&gt;Who We Get Information From and How Your Information Is Used&lt;/h2&gt;&#13;
&lt;p&gt;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Whenever you use any website, mobile application or other internet service, certain information gets created and logged automatically. The same is true when you visit MediaFire.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;We use your personal information to fulfill our commitment to you and provide you with our Services.  In short, it’s necessary for us to do these things in order to make our Services relevant, interesting and personal to you.  We balance our interests with your rights.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;How we use the information we collect depends in part on which Services you use, how you use them, and any choices you have made about information you provide.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Below are the specific purposes for which we use the information we collect from and about you.&lt;/p&gt;&#13;
&#13;
&lt;p style="text-decoration: underline;"&gt;You give us information yourself voluntarily, when you:&lt;/p&gt;&#13;
&#13;
&lt;ul style="list-style: initial; margin: initial; padding: 0 0 0 40px;"&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;Create and update an account&#13;
	 &lt;p style="padding-left: 40px;"&gt;In order to use certain features, you need to create an account with us. We ask for the bare minimum amount of necessary information - your name and email address, a user ID selected by you, and a, hopefully, complicated and very secure password. Then we assign you a unique identifying number in our database.&lt;/p&gt;&#13;
	 &lt;p style="padding-left: 40px;"&gt;We use this information to authenticate you when you log in and to communicate with you.  Communications may be to onboard you to a particular Service to help you become more proficient in using that Service.  Or, to send you administrative messages and information, notifications about changes to our Services, and updates to our agreements. Additionally, communications could be about Service features, updates, security alerts, technical notices, support and administrative messages, surveys, offers, promotions, events, and provide other news or information which may interest you or other similar messages.&lt;/p&gt;&#13;
	 &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;Make a purchase&#13;
	 &lt;p style="padding-left: 40px;"&gt;If you purchase a subscription or add-ons, you must provide certain payment and billing data to our payment processing partners, including your name, credit card information, billing address, and zip code. We do store purchase history, billing, and payment confirmation information.  We’ll email you invoices confirming your purchase&lt;p&gt;&#13;
	 &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;Contact us directly&#13;
	 &lt;p style="padding-left: 40px;"&gt;If you contact us for support or to report a problem or concern (regardless of whether you have created an account), we collect and store your messages, and other data about you like your name, email address, location, operating system, IP address, and any other data you provide or that we collect through automated means (which we cover below). We use this data to respond to you and research your question or concern.&lt;/p&gt;&#13;
	 &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;Interact with our ads&#13;
	 &lt;p style="padding-left: 40px;"&gt;Our advertisers gather information when you click on or tap ads or watch videos.&lt;/p&gt;&#13;
 &#13;
	 &lt;p style="padding-left: 40px;"&gt;The information is used to show you content that’s relevant, interesting and personal to you and to tailor advertisements across your various devices.  Studying ad results helps us make decisions about our customers advertising preferences.&lt;/p&gt;&#13;
	 &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;Add names and email addresses to share folders and files&#13;
	 &lt;p style="padding-left: 40px;"&gt;To use these features, you provide names and email addresses in order to enable the functionality of the features.&lt;/p&gt;&#13;
	 &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;Add people or designate an administrator or billing representative for a business account&#13;
	 &lt;p style="padding-left: 40px;"&gt;Companies purchase seats on their account for employees or business associates and provide names and email addresses for the person ‘occupying’ each seat purchased.  By necessity, each business account will need to provide contact information for their account administrator and, if different, a billing representative.  If you are an individual registered user and the domain of the primary email address associated with your account is owned by your employer and was assigned to you as an employee of that organization, and your organization wishes to establish a business account, then certain information concerning past use of your individual account may become accessible to that organization’s administrator or group of users.&lt;/p&gt;&#13;
	 &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;Share your information from other companies, such as Facebook, Twitter and Google&#13;
	 &lt;p style="padding-left: 40px;"&gt;You may allow transmission of your personal information from companies like these, which may be controlled in the settings of each website, not by MediaFire.   MediaFire does not ask for information about you.&lt;/p&gt;&#13;
	 &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;Provide information at an event we sponsor or participate in&#13;
	 &lt;p style="padding-left: 40px;"&gt;Your name, contact, and possibly other information, may be recorded on our servers.&lt;/p&gt;&#13;
	 &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;Your administrator integrates our Services with other services you use&#13;
	 &lt;p style="padding-left: 40px;"&gt;To do this, you will need an account.&lt;/p&gt;&#13;
	 &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;File a DMCA claim with us&#13;
	 &lt;p style="padding-left: 40px;"&gt;When you file a DMCA claim, you provide information about who you are. All the info will be kept on our servers.&lt;/p&gt;&#13;
	 &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;Accept our Terms of Service and Privacy Policy&#13;
	 &lt;p style="padding-left: 40px;"&gt;You must accept our agreements in order to use our Services and we record your clicked acceptance.&lt;/p&gt;&#13;
	 &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;Apply for a job&#13;
	 &lt;p style="padding-left: 40px;"&gt;When a person applies for a job with MediaFire thru our website, all information is recorded and maintained on our servers.   Applications received in person or by mail will be manually processed and your name and contact information will be entered into forms stored on our servers.&lt;/p&gt;&#13;
	 &lt;/li&gt;&#13;
&#13;
&lt;/ul&gt;&#13;
&#13;
&lt;p style="text-decoration: underline;"&gt;Our systems and/or third parties may automatically obtain information:&lt;/p&gt;&#13;
&lt;p&gt;&lt;/p&gt;&#13;
&#13;
&lt;ul style="list-style: initial; margin: initial; padding: 0 0 0 40px;"&gt;&#13;
&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt; Third-party platforms you connect with&#13;
	 &lt;p style="padding-left: 40px;"&gt;An example would be logging into MediaFire from Facebook.   We need to ensure it’s you, so information is passed to us.  You should review the privacy policies of every website you visit.  Websites use cookies to track users and gather information. &lt;/p&gt;&#13;
	 &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;Information about your device(s)&#13;
	 &lt;p style="padding-left: 40px;"&gt;Information about your IP address, device make, model, operating system, version, and data connection type, and platform, in addition to other specifications and information will be automatically gleaned during contact with our Services. &lt;/p&gt;&#13;
 &#13;
	 &lt;p style="padding-left: 40px;"&gt;We may send you push notifications from time-to-time in order to provide updates and other relevant messages related to our Services. These may include information and in-app messages about, new services, new features, etc.&lt;/p&gt;&#13;
 &#13;
	 &lt;p style="padding-left: 40px;"&gt;Devices are discussed in more detail below.&lt;/p&gt;&#13;
	 &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;When you upload, download, collaborate, share files or otherwise interact with our Services&#13;
	 &lt;p style="padding-left: 40px;"&gt;These actions also are subject to the next point below – ‘When you interact with our website or mobile app or API’.&lt;/p&gt;&#13;
 &#13;
	 &lt;p style="padding-left: 40px;"&gt;You can create content, which may contain information about you, and grant permission for others to see, share, edit, copy and download that content based on settings you or your company administrator (if applicable) select.  Some of the collaboration features of the Services display some or all of your profile information to other Service users when you share or interact with specific content.   Under certain circumstances, when you share a file, your display name and profile picture may be displayed on that page, and Service users with permission to view the page can view your profile information as well.  You can confirm whether certain information is visible from within the Services by contacting us or your administrator (if applicable).  Please be aware that any Content posted, including information about you, by you or anyone with access to the Content, that Content may be publicly viewed and indexed by and returned in search results of search engines.&lt;/p&gt;&#13;
	 &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;When you interact with our website or mobile app or API&#13;
	 &lt;p style="padding-left: 40px;"&gt;MediaFire is always looking for ways to make our Services smarter and faster, and more innovative and useful to you.  We use collective learnings about how people use our Services so we may identify areas for integration and improvement, and feedback provided directly to us to troubleshoot our Services.&lt;/p&gt; &#13;
 &#13;
&lt;p style="padding-left: 40px;"&gt;To that end, when you interact with us, or really any technology service today, information is gathered to help us fulfill our commitments to you to provide and protect our Services and you.  To do that, we need:&lt;/p&gt;&#13;
&#13;
&lt;p style="padding-left: 40px;"&gt;&lt;b&gt;Information about your behavior on MediaFire:&lt;/b&gt; including, login details, date/time of visits, page view data, URL of the Web page you visited before navigating to us, referring/exit pages, click data, features you use, types of advertisements you interact with, duration of your visit, the sizes and names of the files or folders you upload, download, share or access.&lt;/p&gt;&#13;
&#13;
&lt;p style="padding-left: 40px;"&gt;We use this information to personalize and improve our Services, by analyzing who we appeal to, activity patterns and trends, develop new products and services, and test and analyze new features by providing features to some users before rolling the feature out to all users. For example, by logging how often people use two different versions of a feature, we can understand which version is better. &lt;/p&gt;&#13;
&#13;
&lt;p style="padding-left: 40px;"&gt;&lt;b&gt;Information about your devices&lt;/b&gt; plus your browser information, browser history, IP address, the Internet Service Provider (ISP) you use, your geolocation and system configuration information is recorded. &lt;/p&gt;&#13;
 &#13;
&lt;p style="padding-left: 40px;"&gt;This information can help us identify unique users across multiple devices so we can monitor and analyze traffic and trends and track usage and activities in connection with our Services.  We use general location information to provide country based advertising (e.g. US-based advertising, if you are in the US).  We also perform studies necessary to ensure the safety and integrity of our site and mobile applications, monitor and improve the information security, and to facilitate the Services’ technical functioning, including troubleshooting and resolving issues.&lt;/p&gt;&#13;
&#13;
&lt;p style="padding-left: 40px;"&gt;Information may be used as required or permitted by law, or as we, in our sole discretion, otherwise determine to be necessary to ensure the safety and integrity of our users, employees, third parties, the public, or our Services.&lt;/p&gt;&#13;
	 &lt;/li&gt;&#13;
&#13;
&lt;/ul&gt;&#13;
&#13;
&lt;p style="text-decoration: underline;"&gt;Other companies give us data:&lt;/p&gt;&#13;
&lt;p&gt;&lt;/p&gt;&#13;
&lt;ul style="list-style: initial; margin: initial; padding: 0 0 0 40px;"&gt;&#13;
&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt; We may collect info from third party services we contract with&#13;
	 &lt;p style="padding-left: 40px;"&gt;We work with third-party service providers to provide website and application development, hosting, maintenance, backup, storage, virtual infrastructure, payment processing and fraud detection, analysis and other services for us, which may require them to access or use information about you.  We select only well-established and trusted service partners to access information about you to perform services on our behalf.&lt;/p&gt;&#13;
	 &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;Information related to your use of third-party services&#13;
	 &lt;p style="padding-left: 40px;"&gt;The information we receive when you link or integrate our Services with a third-party service depends on the settings, permissions and privacy policy controlled by that third-party service. You should always check the privacy settings and notices in these third-party services to understand what data may be disclosed to us or shared with our Services.&lt;/p&gt;&#13;
&#13;
	 &lt;p style="padding-left: 40px;"&gt;Have you ever searched for information on a mailbox and then when you visit other websites you see ads for mailboxes?  We contract with advertising companies that will use your previous search history and clicks to provide advertising of specific interest to you.  Your interests and interactions with ads are not stored on our servers, but we do benefit from this practice.   After all, ads help support our website and the experience should be of interest to you.&lt;/p&gt;&#13;
	 &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;When you engage in an online survey initiated by us&#13;
	 &lt;p style="padding-left: 40px;"&gt;From time to time, we may perform research (online and offline) via surveys. We may engage third-party service providers to conduct such surveys on our behalf. All survey responses are voluntary, and the information collected will be used for research and reporting purposes to help us better serve our users, as a whole, by learning more about their needs and the quality of the products and services we provide. The survey responses may be utilized to determine the effectiveness of our Website, various types of communications and/or promotional activities, and innovations in products and other service offerings we might contemplate.&lt;/p&gt;&#13;
	 &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;From a social media website&#13;
	 &lt;p style="padding-left: 40px;"&gt;We allow you to use social media sites to create your MediaFire account, sign in to us, or to connect your account with the social media site.  Social media sites may give us automatic access to certain personal information retained by them about you (e.g., content viewed by you, content liked by you, and information about the advertisements you have been shown or have clicked on, etc.).&lt;/p&gt;&#13;
&#13;
	 &lt;p style="padding-left: 40px;"&gt;To sign in from a social media website, such as Facebook or Twitter, information is shared between us to authenticate your identity.  Those platforms and services make information available to us through their APIs. The information we receive depends on what information you or the platform or service decide to give us.  The information we get from those services depends on your settings and their privacy policies, so please check what those are.&lt;/p&gt;&#13;
&#13;
	 &lt;p style="padding-left: 40px;"&gt;If you click on a link provided via a social media plugin, you are voluntarily establishing a connection with that respective social media site.  Services, like Facebook, give you the option to post information from your account with them.  The social media features on our website, like the Facebook Like Button, may allow the third-party social media provider to collect things, such as, your IP address and which page of our Services you’re visiting, and to set a cookie to enable the feature (e.g. Like Button). Your interactions with these features are governed by the social media’s own privacy policy.&lt;/p&gt;&#13;
 &#13;
	 &lt;p style="padding-left: 40px;"&gt;You should be aware that any information you provide on social media websites, community forums and publicly accessible blogs, including profile information associated with the account you use to post the information, may be read, collected, and used by any member of the public who accesses these websites.  Your posts and certain profile information may remain even after you terminate your account. We urge you to consider the sensitivity of any information you input into these Services.&lt;/p&gt;&#13;
	 &lt;/li&gt;&#13;
&#13;
&lt;/ul&gt;&#13;
&#13;
&#13;
&lt;h2&gt;Device Information&lt;/h2&gt;&#13;
&lt;p&gt;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;We automatically receive certain types of information when you install, access, update, or use our Services. This information includes your computer, tablet, mobile or other digital device's unique identifier, manufacturer and model, operating system and version, screen size and resolution,  mobile network  and status (WiFi, etc.), application version including installation and updates info, settings, and crash data that helps us understand when something breaks. Whether we collect some or all of this information often depends on what type of device you’re using and its settings. For example, different types of information are available depending on whether you’re using a Mac or a PC, or an iPhone or Android phone. To learn more about what information your device makes available to us, please also check the policies of your device manufacturer or software provider.  &#13;
&lt;/p&gt;&#13;
&lt;p&gt;We use this information to determine what types and version of devices, etc. are accessing our Services.  After all, we have to write software to accommodate various platforms, versions, etc.   We have to keep up and necessarily sunset unused code.&#13;
&lt;/p&gt;&#13;
&#13;
&#13;
&#13;
&#13;
&#13;
&#13;
					&lt;p&gt;This Privacy Policy governs your use of the MediaFire Services, regardless of how you access it, and by using our Services you consent to the collection, transfer, processing, storage and disclosure and other uses described in this Privacy Policy.  Information may be collected from you in various ways when you use our Services.  We automatically receive certain types of information when you interact with our Web pages, apps, services and communications.  This information includes your computer, tablet, mobile or other digital device's IP address, access times, your browser type and language. We may also collect information about the type of operating system you use, your account activity, and accessed pages.  Personal and non-personally identifiable information from collected data may be shared with third parties who work on our behalf to provide your services.  These third-party services and unique identifiers may be used to contact you, measure usage and analyze trends, administer the website and collect information for its databases. For example:  &lt;a href='http://www.google.com/intl/en/policies/privacy/' target='_blank'&gt;Google Analytics Privacy Policy&lt;/a&gt;.&lt;/p&gt;&#13;
&#13;
&#13;
&#13;
&lt;h2&gt;Cookies, Web Beacons, and Similar Technologies&lt;/h2&gt;&#13;
&lt;p&gt;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;&lt;span style="text-decoration:underline"&gt;What are they?&lt;/style&gt;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;When you interact with people, it’s nice when they remember you, your relationship and what you like.  That ‘feel good’ experience has been extended to your interactions with websites.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Like most browsers and websites, we use technologies that are essentially small data files saved on your computer, tablet, mobile phone, or other devices that allow us to record certain pieces of information whenever you visit or interact with our site, Services, applications, messaging, and tools, and to recognize you across devices.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;MediaFire and service providers acting on our behalf (like Google Analytics and third party advertisers) use server log files and automated data collection tools like cookies, tags, scripts, customized links, device or browser fingerprints, and web beacons when you access and use our Services. These tools are essential to enable the Services to provide the features you have requested, such as remembering you have logged in. These tools also automatically track and collect certain system data and usage data when you use our Services. In some cases, we tie data gathered through these tools to other data that we collect.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;These technologies can operate across all of your browsers, and in some instances may not be fully managed by your browser and may require management directly through your installed applications or device.  The specific names and types of cookies, web beacons, unique identifiers, and similar technologies used to collect and manage information may change from time to time. In order to help you better understand our use of such technologies, we have provided the some terminology and definitions.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;&lt;span style="text-decoration:underline"&gt;Cookies&lt;/span&gt; are mutually beneficial small text files, which often include a unique identifier, placed in the memory of your browser or device when you visit a website or view a message. They are commonly used to remember where you were during your session with a website.  They can be used to collect, store, and share data about your activities across websites.  Cookies allow us to recognize you, remember things about your visits, make our site easier to use, see which areas and features are popular and count visits to our website.  Most web browsers are set to accept cookies by default. There are several types of cookies:&lt;/p&gt;&#13;
&#13;
&lt;ul style="list-style: initial; margin: initial; padding: 0 0 0 40px;"&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;Session cookies expire at the end of your browser session and allow sites to link your actions during that particular browser session.  They help with navigation on a website and are enabled by default.&#13;
	 &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;Persistent cookies are stored on your device and record information, allowing sites to remember your preferences or actions across multiple sites. They remain until you manually delete them or until they expire.&#13;
	 &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;First-party cookies are created by the website you are visiting and are necessary to keep track of your personal preferences and the current session.  Most web browsers enable first-party cookies by default. If you were to disable first-party cookies, a website could not keep track of your activity as you move from page to page.&#13;
	 &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;Third-party cookies are set by a third party site separate from the site you are visiting.  These are commonly used for advertising, analytics, etc.&#13;
	 &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 20px;"&gt;Flash cookies aka Local Shared Objects (“LSO”) are a small file stored on your computer by a website that uses Adobe’s Flash player technology.  Information stored on a Flash cookie is available to all browsers and is considered a security issue.  When you delete or clear cookies from your browser, you will not necessarily delete the Flash cookies stored on your computer.  MediaFire does not use Flash cookies.&#13;
	 &lt;/li&gt;&#13;
&lt;/ul&gt;&#13;
&#13;
&lt;p&gt;&lt;span style="text-decoration:underline"&gt;Web beacons&lt;/span&gt; are small graphic images (also known as "pixel tags" or "clear GIFs") that typically work in conjunction with cookies to identify users and user behavior.  There are myriad ways in which they can be used.  For example, a third-party tracking site can determine how much merchandise was purchased for a particular banner ad campaign. In scenarios such as these, the individual users may still remain anonymous, even though their buying habits are disclosed.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;&lt;span style="text-decoration:underline"&gt;Mobile device identifiers&lt;/span&gt;  - When you access mobile applications, companies don’t have access to traditional browser cookies to track you over time. Instead, third party advertising and analytics companies use device identifiers, such as Apple iOS’s Identifiers for Advertisers and Google Android’s Advertising ID, to monitor the different applications used on a particular device.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;&lt;span style="text-decoration:underline"&gt;Device fingerprinting&lt;/span&gt; can track devices over time, based on your browser’s &#13;
configurations and settings. Because each browser is unique, device fingerprinting can identify your device, without using cookies. Since device fingerprinting uses the characteristics of your browser configuration to track you, deleting cookies won’t help. Device fingerprinting technologies are evolving and can be used to track you on all kinds of internet-connected devices that have browsers, such as smart phones, tablets, laptop and desktop computers. &lt;/p&gt;&#13;
&#13;
&lt;p&gt;&lt;span style="text-decoration:underline"&gt;HTML5&lt;/span&gt; has been designed to deliver almost everything you'd want to do online without requiring additional software such as browser plugins. It does everything from animation to apps, music to movies, and can also be used to build incredibly complicated applications that run in your browser.  And, it can generally be used as an alternative to Adobe Flash.  It isn't proprietary and it is cross-platform, which means it doesn't care whether you're using a tablet or a smartphone, a netbook, notebook or ultrabook or a Smart TV.  If your browser supports HTML5, it should work flawlessly.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;&lt;span style="text-decoration:underline"&gt;Why does MediaFire use these technologies?&lt;/span&gt;&lt;/p&gt;&#13;
&lt;p&gt;MediaFire and our third-party partners, such as our advertising and analytics partners, use cookies and other tracking technologies to provide you with a better, faster, and safer experience, increased functionality and to recognize you across different services and devices.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;We use these cookies both when you visit our site and Services via a browser and our mobile app. As we adopt additional technologies, we may also gather additional data through other methods.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Our cookies and similar technologies have different functions. They are either necessary for the functioning of our services, help us improve our performance, give you extra functionalities, or help us to serve you relevant and targeted ads. We use cookies and similar technologies that only remain on your device for as long as you keep your browser active (session) and cookies and similar technologies that remain on your device for a longer period (persistent). You are free to block, delete, or disable these technologies if your device allows this, but if you disable them, then certain functionalities will break or be unavailable.  You can manage your cookies and your cookie preferences in your browser or device settings.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;To help Us help You to …&lt;/p&gt;&#13;
&#13;
&lt;ul style="list-style: initial; margin: initial; padding: 0 0 0 40px;"&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;save your registration ID and login password for future logins to the Service,&lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;match you to your personal information,&lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;remember your settings and preferences so you don‘t have to set them up every time you visit us, &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;customize your experience and preferences, &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;enable changes you have made in your account,&lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;help us remember the country you’re in,&lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;identify you during a single browsing session as you move around on the pages, &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;Identify you across different browser sessions and devices, &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;remember the user-interface customization cookies (i.e. the parameters attached to your device including your screen resolution, font preference, etc),&lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;enable processing and management of your purchases,&lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;respond to your questions and otherwise interact with you,&lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;allow sharing of your Content on social media &lt;/li&gt;&#13;
&lt;/ul&gt;&#13;
&#13;
&lt;p&gt;&lt;/p&gt;&#13;
&lt;p&gt;To help Us …&lt;/p&gt;&#13;
&#13;
&lt;p style="padding: 0 0 0 25px;"&gt;For Our Website, to …&lt;/p&gt;&#13;
&#13;
&lt;ul style="list-style: initial; margin: initial; padding: 0 0 0 40px;"&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;allow proper functioning of our website/apps,&lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;enable certain features of the Service, &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;properly display Content,&lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;allow you access to our sites, services, applications, and tools,&lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;help us provide a faster, more secure experience, and&lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;identify irregular site behavior, prevent fraudulent activity and improve security. &lt;/li&gt;&#13;
&lt;/ul&gt;&#13;
&#13;
&lt;p style="padding: 20px 0 0 25px;"&gt;For Performance and Analytics, to …  &lt;/p&gt;&#13;
&#13;
&lt;ul style="list-style: initial; margin: initial; padding: 0 0 0 40px;"&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;know how you discovered our websites / app,&lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;to monitor aggregate usage and web traffic routing on the Service,&lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;To avoid visitors being counted twice;&lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;to better understand how users interact with the Service by collecting information about the pages you view, the links you click, and other actions you take when using our Services, &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;identify whether a page was visited, &lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;understand which areas and features of the Services are most popular,&lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;know users’ reaction to subscription offerings,&lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;to assess the performance of our websites, applications, services, and tools, and&lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;gather information about devices and networks utilized to access our Services.&lt;/li&gt;&#13;
&lt;/ul&gt;&#13;
&#13;
&lt;p style="padding: 20px 0 0 25px;"&gt;For the Future, to …&lt;/p&gt;&#13;
&#13;
&lt;ul style="list-style: initial; margin: initial; padding: 0 0 0 40px;"&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;improve our websites/apps by testing new versions and features, and&lt;/li&gt;&#13;
	 &lt;li style="display: list-item; margin-bottom: 5px;"&gt;understand how you interact with our Service so we can improve the Service and your experience based on that information.&lt;/li&gt;&#13;
&lt;/ul&gt;&#13;
&#13;
&#13;
&#13;
&lt;p&gt;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Third-party websites or services linked to MediaFire are not covered by this Privacy Policy. MediaFire is not responsible for the privacy practices of the third-party websites and companies or what they do with your information. You should make sure their privacy policy is acceptable to you.  These websites may collect personally and non-personally identifiable information about you utilizing cookies, web beacons, log data analysis, API, SDK, JavaScript, pixels or other technologies or methods and place cookies on your browser in order to provide advertisement about goods and services likely to be of greater interest to you.  To learn more about behavioral advertising practices or to opt-out of this type of advertising, you can visit the websites of the Digital Advertising Alliance at &lt;a href='http://www.aboutads.info' target='_blank'&gt;http://www.aboutads.info&lt;/a&gt; and  Network Advertising Initiative (NAI) at &lt;a href='http://www.networkadvertising.org/choices/' target='_blank'&gt;http://www.networkadvertising.org/choices/&lt;/a&gt;. You will still see ads if you opt out of behavioral advertising but the ads will be less relevant to you.  Also note that deleting browser cookies can remove your opt-out preferences.&lt;/p&gt;&#13;
&#13;
&#13;
&#13;
&#13;
&lt;h2&gt;Our Policy Concerning Children&lt;/h2&gt;&#13;
&lt;p&gt;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;MediaFire’s Websites and Services are not intended for, nor designed to attract, individuals under the age of sixteen and we recognize the privacy interests of children. &lt;/p&gt;&#13;
&#13;
&lt;p&gt;We realize that children have access to the internet and visit websites.  However, if you are under the age of 16, please do not submit any personal information through our Websites or Services.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;We encourage parents and legal guardians to monitor and take an active role in their children’s online activities and interests and to help enforce this Policy by instructing their children never to provide personal information through Websites or Services without their permission.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;If a parent or guardian becomes aware that "his" child has provided us with personal information, "he" should delete the account. If we become aware that a child under 16 has provided us with personal information, we will take responsible steps to delete the account. For assistance, &lt;a href="/help/submit_a_ticket.php"&gt;contact our support department&lt;/a&gt;.&lt;/p&gt;&#13;
					&#13;
					&#13;
&#13;
&#13;
&#13;
&#13;
&#13;
&#13;
&#13;
&#13;
					&lt;p&gt;If you are not a resident of the United States, you understand and agree that MediaFire stores and processes your information on computers located in the United States, and by providing any data to MediaFire, you consent to the transfer of such information to the United States.&lt;/p&gt;&#13;
&#13;
					&lt;p&gt;We will not rent or sell your personally identifiable information with third parties.  However, we may disclose your personal information or any of its log file information when we have a good faith belief that disclosure is reasonably necessary to (a) comply with a law, regulation or compulsory legal request; (b) co-operate with the investigations of purported unlawful activities; (c) identify persons who may be violating the law or legal notice; (d) protect and defend the rights or property of MediaFire or third parties; (e) protect the safety of an individual or group; (f) prevent fraud or abuse of MediaFire or its users.&lt;/p&gt;&#13;
&#13;
					&#13;
&#13;
					&#13;
	&#13;
					&lt;p&gt;The security of your information is important to us.  MediaFire employs measures to protect information collected from loss, destruction, disclosure, unauthorized access, misuse and alteration.  Although we strive to protect your personal information, MediaFire cannot ensure or warrant the security of any information you transmit to us, and you do so at your own risk.  Sensitive data such as credit card information is administered in compliance with PCI standards.  Customers banking and credit card information is stored, transmitted to, accessed and managed exclusively by any third party payment processors MediaFire may utilize.&lt;/p&gt;&#13;
&#13;
&#13;
&lt;h2&gt;International Information Transfers&lt;/h2&gt;&#13;
&lt;p&gt;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;MediaFire is a United States company and our datacenter is located in the United States. To facilitate our global operations and provide services to you, we transfer information to the United States and allow access to that information other locations outside of your state, province, country, or other governmental jurisdiction, as requested by you, and for the purposes described in this policy.&#13;
&lt;/p&gt;&#13;
&#13;
&lt;p&gt;MediaFire transfers personal data only in a secure and lawful way.  We always do our best to protect your personal data and once we have received it; we use strict procedures and security features to try to prevent unauthorized access.  MediaFire utilizes industry-standard technical, administrative, and physical safeguards to help protect the information on our servers against unauthorized access, alteration, disclosure or destruction.  You are responsible for maintaining the secrecy of your own passwords. If you have reason to believe that your password or personal data is no longer secure, please promptly &lt;a href="/help/submit_a_ticket.php"&gt;contact our support department&lt;/a&gt;.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Your personal information may be transmitted to a third party who may have their servers in a different country, for purposes such as processing transactions, to facilitate payments, and provide support services. As some countries may have laws which are different, and potentially not as protective as the laws of your own country, governing the use and transfer of personal data, we take steps to make sure that our contracted third parties adhere to the commitments set out in this Policy. These steps may include reviewing third parties’ privacy and security standards.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;If you have questions concerning the transfer of your information, please contact us at privacy@mediafire.com&lt;/p&gt;&#13;
&#13;
&#13;
&#13;
&#13;
&lt;h2&gt;Law enforcement, legal proceedings, and in the interest of Others&lt;/h2&gt;&#13;
&lt;p&gt;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Stewardship of your information and data is critical to us and a responsibility that we embrace. However, in certain situations, we may be required to disclose information.   Disclosures may be in response to lawful requests by law enforcement, government agencies, courts, or authorized third-parties, to meet national security or law enforcement requirements, respond to subpoenas, court orders, or legal process, to establish or exercise our legal rights or defend against legal claims, or as otherwise required by law.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;We may also share personal information if we believe it is necessary in order to investigate, prevent, or take action regarding illegal activities, situations involving potential threats to property or the physical safety of any person, in connection with an investigation of fraud, intellectual property infringement, piracy, abuse of MediaFire, our Services, or our users, to protect our network and physical assets, and for violations of our Service Agreements, or other unlawful activity.&lt;/p&gt;&#13;
&#13;
&#13;
&lt;h2&gt;Notification of Modifications to This Privacy Policy&lt;/h2&gt;&#13;
&lt;p&gt;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;We may change this policy from time to time.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Minor changes will become effective immediately upon posting on the website.   If there are material changes to this Policy, you will be notified to view the new policy and give your consent. A revised Privacy Policy supersedes all previous Privacy Policies.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;We encourage you to review our Privacy Notice whenever you access our Services to stay informed about our information practices and the ways you can help protect your privacy. If you disagree with any changes to this Privacy Notice and do not wish your information to be subject to the revised Privacy Notice, your only remedy, if you do not accept the terms of this Policy, is to discontinue use of the Website and the Services. Your use of any of our Services after the posting of changes shall constitute your consent to the changes.&lt;/p&gt;&#13;
&#13;
&lt;h2&gt;Business Transfers&lt;/h2&gt;&#13;
&lt;p&gt;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;We may assign or transfer this Policy, as well as your account and related information and data, including any personal information, to any person or entity that acquires all or substantially all of our business or assets, or with whom we merge or acquire.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;In the unlikely event of our bankruptcy, insolvency, reorganization, receivership, or assignment for the benefit of creditors, or the application of laws or equitable principles affecting creditors' rights generally, MediaFire may not be able to control how your personal information is treated, transferred or used.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;You will be notified via email and/or a prominent notice placed on the Services if a transaction takes place, as well as any choices you may have regarding your information.&lt;/p&gt;&#13;
&#13;
&lt;h2&gt;Contact Us&lt;/h2&gt;&#13;
&lt;p&gt;&lt;/p&gt;&#13;
&#13;
&lt;p&gt;MediaFire would like to hear from you if you have an unresolved privacy or data use concern, questions or need more information about our privacy practices, would like further information concerning the legal basis on which we collect and use your Information, or if you would like to exercise any of your rights above. Please feel free to contact our privacy team (including our designated personal information protection manager) at privacy@mediafire.com. You can also send postal mail to us at MediaFire, Attn: Privacy, 6606 FM1488, Suite 148-322, Magnolia, Texas, 77354.&#13;
&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Your right to file complaints with a data protection supervisory authority remains unaffected by also contacting us directly.&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Thank you for choosing to use MediaFire!&lt;/p&gt;&#13;
&#13;
&lt;p&gt;Last update:  May 25, 2018&lt;/p&gt;</terms><date>2018-07-12 17:35:40</date><date_utc>2018-07-12T22:35:40Z</date_utc></privacy_policy><max_keys>500</max_keys><max_objects>6000</max_objects><max_image_size>26214400</max_image_size><result>Success</result><current_api_version>1.5</current_api_version></response>
